model_list:
  - model_name: gemini-3-pro-preview
    litellm_params:
      model: gemini/gemini-3-pro-preview
      api_key: "os.environ/GEMINI_API_KEY"

# litellm_settings:
#   master_key: "os.environ/LITELLM_MASTER_KEY"
