[general]
  live_config_reload = true

[env]
  TERM = "alacritty" #xterm-256color

[window]
  dimensions = {columns = 0, lines = 0}
  padding = {x = 5, y = 5}
  startup_mode = "Maximized"
  option_as_alt = "Both"

[font]
  normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
  bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}
  italic = {family = "JetBrainsMono Nerd Font", style = "Italic"}
  bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
  size = 17.0

[colors]
  draw_bold_text_with_bright_colors = true
  
[selection]
  save_to_clipboard = false

[cursor]
  style = { shape = "Beam", blinking = "On" }

[[hints.enabled]]
    regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|http:|https:|news:|file:|git:|ssh:|ftp:)[a-zA-Z0-9._?=%&/\\-~@#$!:,]*"
    command = { program = "open-url", args = [] } # Or "open" on macOS, etc.
    hyperlinks = true
    mouse.enabled = true
    binding = { key = "U", mods = "Control|Shift" }

# shell:
#   program: /bin/zsh --login

# key_bindings:
#   - { key: N, mods: Alt| Option| Super, action: None }
#   #- { key: N, mods: Super|Shift, action: SpawnNewInstance }
#   - { key: PageUp,  action: ScrollLineUp }
#   - { key: PageDown, action: ScrollLineDown }

